### ISSUE TITLE
how to deploy in docker ?

### ISSUE THREAD

**Issue by AlbertNie** [deepjavalibrary/djl-spring-boot-starter#29]
I deploy in docker on base JDK8 docker images, but APP start fail with error:
/lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /root/.djl.ai/pytorch/1.9.1-cpu-linux-x86_64/libc10.so)

**Comment by lanking520** [comment]
Looks like your container's GLIBC version is too low. This is due to the docker base system version is too low. If you are planning to use an older system like CentOS7, you should use https://docs.djl.ai/engines/pytorch/pytorch-engine/index.html#for-pre-cxx11-build this instead

**Comment by AlbertNie** [comment]
That's great !
I update sys to ubuntu 18, it works well .
thank you !
