### ISSUE TITLE
Failed v0.26 release

### ISSUE THREAD

**Issue by tzolov** [deepjavalibrary/djl-spring-boot-starter#36]
Looks like the v0.26 release has filed to publish both the release and snapshot artifacts:
<img width="1438" alt="Screenshot 2024-01-20 at 12 55 26" src="https://github.com/deepjavalibrary/djl-spring-boot-starter/assets/1351573/d7a22b65-ffe4-4a5a-85fa-379a9b54d48a">

https://github.com/deepjavalibrary/djl-spring-boot-starter/actions

**Comment by frankfliu** [comment]
This failure is caused by JDK 17 upgrade. I created a PR to address this issue: https://github.com/deepjavalibrary/djl-spring-boot-starter/pull/37

**Comment by frankfliu** [comment]
0.26 has been released
